import { useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { ExternalLink, MonitorPlay } from 'lucide-react'
import { AdminLayout } from '../components/AdminLayout'
import { StatCard } from '../components/StatCard'
import { StatusBadge } from '../components/StatusBadge'
import { QueueTable } from '../components/Tables'
import { QueueActionPanel, QueueStatusBanner } from '../components/QueuePanels'
import {
  CallNextModal,
  ChangeRoomModal,
  PatientAbsentModal,
  PauseQueueModal,
  ReportDelayModal,
  ResumeQueueModal,
} from '../components/QueueModals'
import { useAdmin, waitingCount } from '../adminContext'

type Dialog = 'call' | 'pause' | 'resume' | 'delay' | 'room' | 'absent' | null

export default function AdminQueueDetail() {
  const { deptId = 'medicine' } = useParams()
  const {
    getDepartment,
    callNext,
    pauseQueue,
    resumeQueue,
    reportDelay,
    changeRoom,
    markAbsent,
    alerts,
  } = useAdmin()

  const [dialog, setDialog] = useState<Dialog>(null)
  const [selected, setSelected] = useState<string | undefined>()

  const dept = getDepartment(deptId)
  if (!dept) return <Navigate to="/admin/queues" replace />

  const waiting = waitingCount(dept)
  const nextEntry = dept.queue.find((q) => q.status === 'next')
  const nextToken = nextEntry?.token ?? '—'
  const estimate = Math.max(5, waiting * 3)

  // The most recent message SmartQueue generated for this OPD — proof that
  // the operational change reached patients.
  const lastAlert = alerts.find((a) => a.department === dept.fullName)

  return (
    <AdminLayout>
      <div className="mb-6 flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex flex-wrap items-center gap-3">
            <h1 className="display text-[30px] text-ivory">{dept.fullName}</h1>
            <StatusBadge state={dept.state} variant="full" />
          </div>
          <p className="mt-1.5 text-[14.5px] text-muted">
            {dept.room} · {dept.doctor}
          </p>
        </div>

        <div className="flex flex-wrap gap-2.5">
          <button
            type="button"
            className="inline-flex items-center gap-2 rounded-lg border border-admin-line-2 px-4 py-2.5 text-[13.5px] font-medium text-ivory-2 transition-colors duration-200 hover:border-gold/45"
          >
            <MonitorPlay className="h-[16px] w-[16px] text-gold" strokeWidth={1.7} aria-hidden />
            View on Display
          </button>
          <Link
            to="/queue"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded-lg border border-admin-line-2 px-4 py-2.5 text-[13.5px] font-medium text-ivory-2 transition-colors duration-200 hover:border-sage/45 hover:text-sage"
          >
            <ExternalLink className="h-[16px] w-[16px]" strokeWidth={1.7} aria-hidden />
            View Patient Experience
          </Link>
        </div>
      </div>

      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Now Serving" value={dept.nowServing} tone="gold" />
        <StatCard label="Waiting" value={waiting} unit="patients" />
        <StatCard label="Next" value={nextToken} />
        {/* Kept deliberately quiet: a range, never a promised time. */}
        <StatCard
          label="Estimated Wait"
          value={<span className="text-[22px] text-muted">~{estimate} min</span>}
          tone="muted"
          hint="Indicative only"
        />
      </div>

      {dept.state !== 'normal' && (
        <div className="mb-6">
          <QueueStatusBanner dept={dept} />
        </div>
      )}

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]">
        <div className="flex flex-col gap-5">
          <QueueTable queue={dept.queue} selected={selected} onSelect={setSelected} />

          {lastAlert && (
            <section className="rounded-xl border border-admin-line bg-admin-card p-5">
              <h2 className="text-[15px] font-semibold text-ivory">
                Latest patient notification
              </h2>
              <p className="mt-1 text-[13px] text-muted-2">
                Generated by SmartQueue from the queue state — staff do not write these.
              </p>
              <p className="mt-3.5 rounded-lg border border-sage/20 bg-sage/6 px-4 py-3 text-[13.5px] leading-relaxed text-ivory-2">
                {lastAlert.message}
              </p>
              <p className="mt-2.5 text-[12.5px] text-muted-2">
                Sent {lastAlert.sentAt} · {lastAlert.recipients}{' '}
                {lastAlert.recipients === 1 ? 'patient' : 'patients'} notified
              </p>
            </section>
          )}
        </div>

        <QueueActionPanel
          dept={dept}
          selectedToken={selected}
          onCallNext={() => setDialog('call')}
          onPause={() => setDialog('pause')}
          onResume={() => setDialog('resume')}
          onReportDelay={() => setDialog('delay')}
          onChangeRoom={() => setDialog('room')}
          onAbsent={() => setDialog('absent')}
        />
      </div>

      {/* ---------------- dialogs ---------------- */}
      <CallNextModal
        open={dialog === 'call'}
        onClose={() => setDialog(null)}
        dept={dept}
        nextToken={nextToken}
        onConfirm={() => callNext(dept.id)}
      />
      <PauseQueueModal
        open={dialog === 'pause'}
        onClose={() => setDialog(null)}
        dept={dept}
        waiting={waiting}
        onConfirm={(reason) => pauseQueue(dept.id, reason)}
      />
      <ResumeQueueModal
        open={dialog === 'resume'}
        onClose={() => setDialog(null)}
        dept={dept}
        waiting={waiting}
        onConfirm={() => resumeQueue(dept.id)}
      />
      <ReportDelayModal
        open={dialog === 'delay'}
        onClose={() => setDialog(null)}
        dept={dept}
        waiting={waiting}
        onConfirm={(reason, window) => reportDelay(dept.id, reason, window)}
      />
      <ChangeRoomModal
        open={dialog === 'room'}
        onClose={() => setDialog(null)}
        dept={dept}
        waiting={waiting}
        onConfirm={(room) => changeRoom(dept.id, room)}
      />
      <PatientAbsentModal
        open={dialog === 'absent'}
        onClose={() => setDialog(null)}
        token={selected ?? ''}
        onConfirm={(action) => selected && markAbsent(dept.id, selected, action)}
      />
    </AdminLayout>
  )
}
